FROM ubuntu:20.04

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
        cmake \
        g++-aarch64-linux-gnu \
        gcc-aarch64-linux-gnu \
        make \
    && rm -rf /var/lib/apt/lists/*
