#!/bin/bash
set -euo pipefail

MODEL_DIR="${1:-/data/hymt}"
BIN="${MODEL_DIR}/hymt_demo"
REPEATS="${REPEATS:-5}"

run_repeated() {
    local name="$1"
    local max_new_tokens="$2"
    local prompt="$3"
    local repeat
    for ((repeat = 1; repeat <= REPEATS; repeat++)); do
        echo "===== ${name} repeat=${repeat}/${REPEATS} ====="
        "${BIN}" "${MODEL_DIR}" "${prompt}" "${max_new_tokens}"
    done
}

run_repeated short 128 'Translate the following segment into Chinese, without additional explanation.\n\nIt’s on the house.'
run_repeated medium 192 'Translate the following segment into Chinese, without additional explanation.\n\nDuring autoregressive decoding, the model reuses the key-value cache generated by previous tokens. This avoids recomputing the full attention history, but memory bandwidth can still become a bottleneck when the context grows.'
run_repeated long 256 'Translate the following segment into Chinese, without additional explanation.\n\nBefore deploying the service, the engineering team must complete three checks. First, it should compare the converted model against a deterministic reference on short, medium, and long inputs. Second, it should record latency after a warm-up period instead of relying on a single cold-start measurement. Finally, it should preserve the previous model so that operators can roll back quickly if accuracy or stability declines. A release may proceed only when all checks pass and the results are documented.'
