#!/bin/bash
# HY-MT W4BF16 扩展回归（46 用例：16 原有 + 30 新增，覆盖多语言对/术语/格式/数字/科技/金融/长文）
# 用法: MODEL_DIR=${1:-/data/hymt_w4g64} REPEATS=${REPEATS:-1} bash board_regression_w4_extended.sh
set -euo pipefail

MODEL_DIR="${1:-/data/hymt_w4g64}"
BIN="${BIN:-${MODEL_DIR}/hymt_demo}"
REPEATS="${REPEATS:-1}"

run_case() {
    local name="$1"
    local max_new_tokens="$2"
    local prompt="$3"
    local repeat
    for ((repeat = 1; repeat <= REPEATS; repeat++)); do
        echo "===== ${name} repeat=${repeat}/${REPEATS} ====="
        "${BIN}" "${MODEL_DIR}" "${prompt}" "${max_new_tokens}"
    done
}

# ---------- 原有 16 用例 ----------
run_case en_zh_short 128 'Translate the following segment into Chinese, without additional explanation.\n\nIt’s on the house.'
run_case zh_en_short 128 '将以下文本翻译为英语，注意只需要输出翻译后的结果，不要额外解释：\n\n这个方案需要在周五之前完成。'
run_case ja_zh_short 128 'Translate the following segment into Chinese, without additional explanation.\n\nこの電車は東京駅に止まりますか。'
run_case terminology_short 128 '参考下面的翻译：\n算能 翻译成 Sophon\n\n将以下文本翻译为英语，注意只需要输出翻译后的结果，不要额外解释：\n算能的处理器适合边缘推理。'
run_case formatting_short 128 '将以下<source></source>之间的文本翻译为中文，注意只需要输出翻译后的结果，不要额外解释，原文中的<sn></sn>标签表示标签内文本包含格式信息，需要在译文中相应的位置尽量保留该标签。输出格式为：<target>str</target>\n\n<source>Install <sn>transformers==4.56.1</sn> before running the model.</source>'
run_case en_zh_medium_news 192 'Translate the following segment into Chinese, without additional explanation.\n\nThe regional rail operator announced on Tuesday that weekend services would run every fifteen minutes, while several downtown stations would close early for maintenance. Passengers were advised to check the updated timetable before leaving home.'
run_case zh_en_medium_business 192 '将以下文本翻译为英语，注意只需要输出翻译后的结果，不要额外解释：\n\n由于原材料价格回落、海外订单逐步恢复，公司第二季度毛利率有所改善。不过，管理层仍然认为汇率波动和物流成本是下半年最主要的不确定因素。'
run_case ja_zh_medium_notice 192 'Translate the following segment into Chinese, without additional explanation.\n\nシステム更新のため、8月15日午前1時から午前4時までオンラインサービスを停止します。作業の進捗によっては、終了時刻が前後する可能性があります。ご不便をおかけしますが、ご理解をお願いいたします。'
run_case en_zh_technical 192 'Translate the following segment into Chinese, without additional explanation.\n\nDuring autoregressive decoding, the model reuses the key-value cache generated by previous tokens. This avoids recomputing the full attention history, but memory bandwidth can still become a bottleneck when the context grows.'
run_case zh_en_technical 192 '将以下文本翻译为英语，注意只需要输出翻译后的结果，不要额外解释：\n\n量化并不一定会按相同比例提升端到端性能。只有当权重读取是主要瓶颈，并且反量化开销足够低时，更小的权重格式才会带来明显收益。'
run_case en_zh_numbers_units 128 'Translate the following segment into Chinese, without additional explanation.\n\nThe device processed 12,480 requests in 37.5 seconds, consumed an average of 42 W, and kept its temperature below 68°C throughout the test.'
run_case zh_en_names_dates 128 '将以下文本翻译为英语，注意只需要输出翻译后的结果，不要额外解释：\n\n李明将于2026年9月3日在深圳参加Edge AI Summit，并在下午2:30介绍新一代推理平台。'
run_case en_zh_long_policy 256 'Translate the following segment into Chinese, without additional explanation.\n\nBefore deploying the service, the engineering team must complete three checks. First, it should compare the converted model against a deterministic reference on short, medium, and long inputs. Second, it should record latency after a warm-up period instead of relying on a single cold-start measurement. Finally, it should preserve the previous model so that operators can roll back quickly if accuracy or stability declines. A release may proceed only when all checks pass and the results are documented.'
run_case zh_en_long_report 256 '将以下文本翻译为英语，注意只需要输出翻译后的结果，不要额外解释：\n\n本次测试采用固定随机种子和贪心解码，以便比较不同量化版本的输出。测试集同时包含短句、技术段落、数字单位、专有名词和带标签的文本。每个性能用例在预热后重复运行多次，并分别记录首个词元延迟和后续解码速度。如果低比特模型虽然更快，但在长文本中出现遗漏、重复或术语错误，就不能直接替换当前的高精度版本。'
run_case formatting_medium 192 '将以下<source></source>之间的文本翻译为中文，注意只需要输出翻译后的结果，不要额外解释，并保留原文中的XML标签和命令。输出格式为：<target>str</target>\n\n<source>Set <code>MAX_LENGTH=512</code>, restart <product>Sophon Service</product>, and verify that the status is <b>healthy</b>.</source>'
run_case terminology_medium 192 '参考下面的翻译：\n算能 翻译成 Sophon\n张量处理器 翻译成 tensor processor\n边缘推理 翻译成 edge inference\n\n将以下文本翻译为英语，注意只需要输出翻译后的结果，不要额外解释：\n算能团队使用张量处理器优化了边缘推理服务，同时保留了可回退的高精度模型。'

# ---------- 新增 30 用例 ----------
# 短句·生活场景（en→zh）
run_case en_zh_daily_greeting 128 'Translate the following segment into Chinese, without additional explanation.\n\nThanks for waiting, your table is ready now.'
run_case en_zh_daily_weather 128 'Translate the following segment into Chinese, without additional explanation.\n\nIt looks like rain this afternoon, so bring an umbrella.'
run_case en_zh_daily_travel 128 'Translate the following segment into Chinese, without additional explanation.\n\nThe next train to the airport departs from platform three.'
run_case en_zh_daily_shopping 128 'Translate the following segment into Chinese, without additional explanation.\n\nThis jacket comes in black, navy, and olive green.'
run_case en_zh_daily_meeting 128 'Translate the following segment into Chinese, without additional explanation.\n\nLet us move the stand-up meeting to nine thirty tomorrow.'
run_case en_zh_daily_email 128 'Translate the following segment into Chinese, without additional explanation.\n\nPlease find the updated invoice attached to this email.'

# 短句·生活场景（zh→en）
run_case zh_en_daily_greeting 128 '将以下文本翻译为英语，注意只需要输出翻译后的结果，不要额外解释：\n\n早上好，欢迎光临，请问需要喝点什么？'
run_case zh_en_daily_weather 128 '将以下文本翻译为英语，注意只需要输出翻译后的结果，不要额外解释：\n\n今天晚些时候会下雨，出门记得带伞。'
run_case zh_en_daily_travel 128 '将以下文本翻译为英语，注意只需要输出翻译后的结果，不要额外解释：\n\n去机场的下一班列车在三号站台发车。'
run_case zh_en_daily_shopping 128 '将以下文本翻译为英语，注意只需要输出翻译后的结果，不要额外解释：\n\n这件夹克有黑色、藏青和橄榄绿三种颜色。'
run_case zh_en_daily_meeting 128 '将以下文本翻译为英语，注意只需要输出翻译后的结果，不要额外解释：\n\n我们把站会改到明天上午九点半吧。'
run_case zh_en_daily_email 128 '将以下文本翻译为英语，注意只需要输出翻译后的结果，不要额外解释：\n\n更新后的发票请查收，附件已附在这封邮件里。'

# 日→中 / 中→日
run_case ja_zh_restaurant 128 'Translate the following segment into Chinese, without additional explanation.\n\nすみません、メニューをいただけますか。'
run_case ja_zh_hotel 128 'Translate the following segment into Chinese, without additional explanation.\n\nチェックアウトは午前11時までです。'
run_case zh_ja_package 128 '将以下文本翻译为日语，注意只需要输出翻译后的结果，不要额外解释：\n\n这个套餐已经包含了两晚的住宿和早餐。'
run_case zh_ja_notice 128 '将以下文本翻译为日语，注意只需要输出翻译后的结果，不要额外解释：\n\n系统将于本周五晚上十点进行维护，届时服务会中断约一小时。'

# 术语与专名
run_case terminology_chip 128 '参考下面的翻译：\n算能 翻译成 Sophon\n\n将以下文本翻译为英语，注意只需要输出翻译后的结果，不要额外解释：\nBM1684X 的算力密度非常适合视频分析场景。'
run_case terminology_edge 128 '参考下面的翻译：\n边缘推理 翻译成 edge inference\n\n将以下文本翻译为英语，注意只需要输出翻译后的结果，不要额外解释：\n边缘推理要求模型在受限的内存和功耗下保持稳定的延迟。'
run_case terminology_nlp 128 '参考下面的翻译：\n机器翻译 翻译成 machine translation\n\n将以下文本翻译为英语，注意只需要输出翻译后的结果，不要额外解释：\n机器翻译的质量评估需要同时考虑流畅性和忠实度。'
run_case names_city_event 128 '将以下文本翻译为英语，注意只需要输出翻译后的结果，不要额外解释：\n\n下周在杭州举办的开发者大会，预计有超过三千名工程师参加。'
run_case names_products 128 '将以下文本翻译为英语，注意只需要输出翻译后的结果，不要额外解释：\n\nQwen3-TTS 支持十二种语言和自定义音色克隆。'
run_case names_abbr 128 'Translate the following segment into Chinese, without additional explanation.\n\nThe new NPU delivers 32 TOPS at 8-bit integer precision.'

# 格式与标签
run_case formatting_code 192 '将以下<source></source>之间的文本翻译为中文，注意只需要输出翻译后的结果，不要额外解释，并保留原文中的XML标签和命令。输出格式为：<target>str</target>\n\n<source>Run <code>cmake -B build</code>, then call <code>make</code> to compile the demo.</source>'
run_case formatting_bold 192 '将以下<source></source>之间的文本翻译为中文，注意只需要输出翻译后的结果，不要额外解释，并保留原文中的XML标签。输出格式为：<target>str</target>\n\n<source>The <b>model</b> is <i>faster</i> than the previous <b>release</b>.</source>'
run_case formatting_mixed 192 '将以下<source></source>之间的文本翻译为中文，注意只需要输出翻译后的结果，不要额外解释，并保留原文中的XML标签。输出格式为：<target>str</target>\n\n<source>Deploy <code>app_3.2</code> to the <b>edge node</b> and restart <code>nginx</code>.</source>'

# 数字与单位
run_case numbers_stats 128 'Translate the following segment into Chinese, without additional explanation.\n\nThe survey covered 3,248 users across 12 regions; 67.3% reported faster page loads.'
run_case numbers_spec 128 '将以下文本翻译为英语，注意只需要输出翻译后的结果，不要额外解释：\n\n峰值带宽 1.6 TB/s，功耗 75 W，待机电流低于 1.2 A。'
run_case numbers_time 128 'Translate the following segment into Chinese, without additional explanation.\n\nThe batch job completes in 2 h 45 min, about three times faster than before.'
run_case numbers_currency 128 'Translate the following segment into Chinese, without additional explanation.\n\nThe upgrade costs 4,200 dollars per node, with a 15 percent discount for orders above ten units.'

# 科技段落
run_case tech_kv_cache 192 'Translate the following segment into Chinese, without additional explanation.\n\nDuring generation, the key-value cache stores the intermediate results of previous tokens, so the model only attends to the new query instead of recomputing the whole history.'
run_case tech_quant_group 192 '将以下文本翻译为英语，注意只需要输出翻译后的结果，不要额外解释：\n\n分组量化以每 64 个元素为一组进行缩放，在降低反量化开销的同时，把误差控制在可接受的范围。'
run_case tech_tpu_sched 192 'Translate the following segment into Chinese, without additional explanation.\n\nThe compiler partitions the graph into layers that fit the on-chip memory, then the scheduler assigns them to the available cores to hide memory latency.'
run_case tech_streaming 192 '将以下文本翻译为英语，注意只需要输出翻译后的结果，不要额外解释：\n\n流式识别把音频切分为一秒的片段，首字延迟可以降到 300 毫秒以内。'

# 新闻与财经
run_case news_market 192 '将以下文本翻译为英语，注意只需要输出翻译后的结果，不要额外解释：\n\n受海外订单回暖影响，公司第二季度营收同比增长 18%，毛利率升至 42%。'
run_case news_policy 192 '将以下文本翻译为英语，注意只需要输出翻译后的结果，不要额外解释：\n\n监管机构要求所有上市企业在年报中披露人工智能模型的使用情况。'
run_case en_news_semiconductor 192 'Translate the following segment into Chinese, without additional explanation.\n\nSemiconductor exports rose for the third straight month, led by demand for advanced packaging and high-bandwidth memory.'
run_case en_news_energy 192 'Translate the following segment into Chinese, without additional explanation.\n\nGrid operators are testing battery storage systems to smooth the evening peak and avoid curtailment of renewable power.'

# 长文本
run_case long_tech_zh 256 '将以下文本翻译为英语，注意只需要输出翻译后的结果，不要额外解释：\n\n在大模型部署中，推理服务通常面临三个挑战。首先，显存带宽决定了每个词元的生成延迟，权重读取往往成为主要瓶颈。其次，动态形状会降低编译器优化效率，因此生产环境通常使用静态输入形状并做填充对齐。最后，多用户并发时缓存竞争会放大尾延迟，需要合理的批处理与调度策略。只有在这些方面同时得到控制，端到端的吞吐和延迟指标才能满足商用要求。'
run_case long_news_en 256 'Translate the following segment into Chinese, without additional explanation.\n\nCity officials unveiled a ten-year transit plan on Monday, including three new subway lines, a dedicated bus corridor, and a network of bicycle lanes connecting the downtown core to twelve surrounding neighborhoods. The first phase is expected to break ground next spring and add roughly forty kilometers of track. Funding will come from a mix of federal grants, municipal bonds, and a modest fare increase approved earlier this year. Advocates welcomed the plan but cautioned that station accessibility and last-mile connections will determine whether the system actually reduces car trips.'
run_case long_report_zh 256 '将以下文本翻译为英语，注意只需要输出翻译后的结果，不要额外解释：\n\n边缘设备数量的快速增长带来了新的计算需求。与云端数据中心不同，边缘设备通常功耗受限、散热条件差，只能容纳尺寸较小的模型。因此，模型压缩与量化成为部署中的关键环节。实验表明，分组量化在保持输出质量的同时，可以把模型体积压缩到原来的四分之一。报告建议在正式上线前完成三天的稳定性测试，覆盖不同负载和网络波动场景，并保留旧版本以便快速回滚。'
run_case long_instruction_en 256 'Translate the following segment into Chinese, without additional explanation.\n\nPlease review the attached proposal before Thursday. The document compares three deployment options for the new speech service: on-premise servers, a managed cloud instance, and the edge gateway that already runs our authentication stack. Option two offers the lowest upfront cost but adds recurring per-minute fees. Option three keeps all audio on site, which simplifies compliance, yet the gateway has limited compute headroom for the streaming decoder. I lean toward a hybrid setup, using the cloud for burst traffic while keeping the default path on the edge. Let me know if you disagree before the vendor call on Friday morning.'

# 标点/符号/口语
run_case punct_zh 128 '将以下文本翻译为英语，注意只需要输出翻译后的结果，不要额外解释：\n\n注意：请勿在「维护窗口」期间重启节点；否则可能丢失缓存（见第 3 节）。'
run_case punct_en 128 'Translate the following segment into Chinese, without additional explanation.\n\nUse the "beta" flag — not the legacy one — when deploying the new agent.'
run_case punctuation_dash 128 '将以下文本翻译为英语，注意只需要输出翻译后的结果，不要额外解释：\n\n验收标准有三条——功能完整、延迟达标、文档齐全——缺一不可。'

# 指令/摘要风格
run_case api_bullet_zh 192 '将以下文本翻译为英语，注意只需要输出翻译后的结果，不要额外解释：\n\n更新内容包括：修复了 4GB 设备上的内存崩溃问题；新增 --batch 批量模式；弃用了 /v1/legacy 旧接口。'

echo "===== ALL DONE (${REPEATS}x46 cases) ====="
