#!/bin/bash
set -euo pipefail

MODEL_DIR="${1:-/data/hymt}"
BIN="${MODEL_DIR}/hymt_demo"
REPEATS="${REPEATS:-3}"

run_case() {
    local name="$1"
    local max_new_tokens="$2"
    local prompt="$3"
    local repeat
    for ((repeat = 1; repeat <= REPEATS; repeat++)); do
        echo "===== ${name} repeat=${repeat}/${REPEATS} ====="
        "${BIN}" "${MODEL_DIR}" "${prompt}" "${max_new_tokens}"
    done
}

run_case en_zh_short 128 'Translate the following segment into Chinese, without additional explanation.\n\nIt’s on the house.'
run_case zh_en_short 128 '将以下文本翻译为英语，注意只需要输出翻译后的结果，不要额外解释：\n\n这个方案需要在周五之前完成。'
run_case ja_zh_short 128 'Translate the following segment into Chinese, without additional explanation.\n\nこの電車は東京駅に止まりますか。'
run_case terminology_short 128 '参考下面的翻译：\n算能 翻译成 Sophon\n\n将以下文本翻译为英语，注意只需要输出翻译后的结果，不要额外解释：\n算能的处理器适合边缘推理。'
run_case formatting_short 128 '将以下<source></source>之间的文本翻译为中文，注意只需要输出翻译后的结果，不要额外解释，原文中的<sn></sn>标签表示标签内文本包含格式信息，需要在译文中相应的位置尽量保留该标签。输出格式为：<target>str</target>\n\n<source>Install <sn>transformers==4.56.1</sn> before running the model.</source>'
run_case en_zh_medium_news 192 'Translate the following segment into Chinese, without additional explanation.\n\nThe regional rail operator announced on Tuesday that weekend services would run every fifteen minutes, while several downtown stations would close early for maintenance. Passengers were advised to check the updated timetable before leaving home.'
run_case zh_en_medium_business 192 '将以下文本翻译为英语，注意只需要输出翻译后的结果，不要额外解释：\n\n由于原材料价格回落、海外订单逐步恢复，公司第二季度毛利率有所改善。不过，管理层仍然认为汇率波动和物流成本是下半年最主要的不确定因素。'
run_case ja_zh_medium_notice 192 'Translate the following segment into Chinese, without additional explanation.\n\nシステム更新のため、8月15日午前1時から午前4時までオンラインサービスを停止します。作業の進捗によっては、終了時刻が前後する可能性があります。ご不便をおかけしますが、ご理解をお願いいたします。'
run_case en_zh_technical 192 'Translate the following segment into Chinese, without additional explanation.\n\nDuring autoregressive decoding, the model reuses the key-value cache generated by previous tokens. This avoids recomputing the full attention history, but memory bandwidth can still become a bottleneck when the context grows.'
run_case zh_en_technical 192 '将以下文本翻译为英语，注意只需要输出翻译后的结果，不要额外解释：\n\n量化并不一定会按相同比例提升端到端性能。只有当权重读取是主要瓶颈，并且反量化开销足够低时，更小的权重格式才会带来明显收益。'
run_case en_zh_numbers_units 128 'Translate the following segment into Chinese, without additional explanation.\n\nThe device processed 12,480 requests in 37.5 seconds, consumed an average of 42 W, and kept its temperature below 68°C throughout the test.'
run_case zh_en_names_dates 128 '将以下文本翻译为英语，注意只需要输出翻译后的结果，不要额外解释：\n\n李明将于2026年9月3日在深圳参加Edge AI Summit，并在下午2:30介绍新一代推理平台。'
run_case en_zh_long_policy 256 'Translate the following segment into Chinese, without additional explanation.\n\nBefore deploying the service, the engineering team must complete three checks. First, it should compare the converted model against a deterministic reference on short, medium, and long inputs. Second, it should record latency after a warm-up period instead of relying on a single cold-start measurement. Finally, it should preserve the previous model so that operators can roll back quickly if accuracy or stability declines. A release may proceed only when all checks pass and the results are documented.'
run_case zh_en_long_report 256 '将以下文本翻译为英语，注意只需要输出翻译后的结果，不要额外解释：\n\n本次测试采用固定随机种子和贪心解码，以便比较不同量化版本的输出。测试集同时包含短句、技术段落、数字单位、专有名词和带标签的文本。每个性能用例在预热后重复运行多次，并分别记录首个词元延迟和后续解码速度。如果低比特模型虽然更快，但在长文本中出现遗漏、重复或术语错误，就不能直接替换当前的高精度版本。'
run_case formatting_medium 192 '将以下<source></source>之间的文本翻译为中文，注意只需要输出翻译后的结果，不要额外解释，并保留原文中的XML标签和命令。输出格式为：<target>str</target>\n\n<source>Set <code>MAX_LENGTH=512</code>, restart <product>Sophon Service</product>, and verify that the status is <b>healthy</b>.</source>'
run_case terminology_medium 192 '参考下面的翻译：\n算能 翻译成 Sophon\n张量处理器 翻译成 tensor processor\n边缘推理 翻译成 edge inference\n\n将以下文本翻译为英语，注意只需要输出翻译后的结果，不要额外解释：\n算能团队使用张量处理器优化了边缘推理服务，同时保留了可回退的高精度模型。'
